#ifndef ESP111_PROTOCOL_COMMON_H
#define ESP111_PROTOCOL_COMMON_H

/**
 * @file esp111_protocol_common.h
 * @brief ESP-111 三套固件共享协议常量。
 *
 * 本头文件同时服务 C5 终端（ESPC51/ESPC52）和 S3 网关（ESPS3）。它只固化字段名、
 * 路径、类型码、错误码、默认身份和音频格式，不实现解析、转发或业务处理。
 *
 * 协议边界：
 * - C5 -> S3 telemetry 使用 UDP/33434 或 /local/v1/stream 的扁平设备流 JSON；
 * - C5 <-> S3 控制/语音使用 /local/v1 和轻量 JSON 字段 p/id/t/u/q/v/cid/c/a/ok/e/cmds；
 * - S3 的 protocol_adapter/server_client 负责两层协议转换和所有 Server 路径；
 * - C5 只保留 /local/v1 轻量边界，不直接构造 Server 完整 envelope。
 */

#ifdef __cplusplus
extern "C" {
#endif

#define ESP111_PROTOCOL_SCHEMA_VERSION 1
#define ESP111_PROTOCOL_SCHEMA_VERSION_STRING "1"
#define ESP111_PROTOCOL_LOCAL_SCHEMA_VERSION 2
#define ESP111_PROTOCOL_LOCAL_SCHEMA_VERSION_STRING "2"
#define ESP111_PROTOCOL_DASHBOARD_SNAPSHOT_SCHEMA_VERSION 2
#define ESP111_PROTOCOL_DASHBOARD_SNAPSHOT_SCHEMA_VERSION_STRING "2"

#define ESP111_PROTOCOL_GATEWAY_ID "sensair_s3_gateway_01"
#define ESP111_PROTOCOL_GATEWAY_ROLE "gateway"
#define ESP111_PROTOCOL_TERMINAL_ROLE "terminal"
#define ESP111_PROTOCOL_TERMINAL_DEVICE_TYPE "sensair_shuttle_terminal"
#define ESP111_PROTOCOL_FIRMWARE_VERSION "0.1.0"
#define ESP111_PROTOCOL_TERMINAL_DEVICE_ID_C51 "sensair_shuttle_01"
#define ESP111_PROTOCOL_TERMINAL_DEVICE_ID_C52 "sensair_shuttle_02"

#define ESP111_PROTOCOL_GATEWAY_SSID "SensaiHub_S3_01"
#define ESP111_PROTOCOL_GATEWAY_PASSWORD "sensaihub123"
#define ESP111_PROTOCOL_GATEWAY_IP "192.168.4.1"

/* C5 终端能力声明：lcd/csi_placeholder 表示保留上层接口，不代表当前接入真实 LCD 或 CSI 算法。 */
#define ESP111_PROTOCOL_TERMINAL_CAPABILITIES_JSON \
    "[\"sensor\",\"mic\",\"speaker\",\"lcd\",\"wake\",\"csi_placeholder\"]"

/* S3 <-> Server 完整 v1 JSON 字段名。C5 本地 body 不直接使用这些长字段。 */
#define ESP111_PROTOCOL_JSON_SCHEMA_VERSION "schema_version"
#define ESP111_PROTOCOL_JSON_MESSAGE_TYPE "message_type"
#define ESP111_PROTOCOL_JSON_GATEWAY_ID "gateway_id"
#define ESP111_PROTOCOL_JSON_DEVICE_ID "device_id"
#define ESP111_PROTOCOL_JSON_ROOM_ID "room_id"
#define ESP111_PROTOCOL_JSON_ALIAS "alias"
#define ESP111_PROTOCOL_JSON_SEQ "request_seq"
#define ESP111_PROTOCOL_JSON_UPTIME_MS "esp_uptime_ms"
#define ESP111_PROTOCOL_JSON_ESP_TIME_MS "esp_time_ms"
#define ESP111_PROTOCOL_JSON_TIMESTAMP_MS "timestamp_ms"
#define ESP111_PROTOCOL_JSON_TIME_SYNCED "time_synced"
#define ESP111_PROTOCOL_JSON_FIRMWARE_VERSION "firmware_version"
#define ESP111_PROTOCOL_JSON_CAPABILITIES "capabilities"
#define ESP111_PROTOCOL_JSON_PAYLOAD "payload"
#define ESP111_PROTOCOL_JSON_PAYLOAD_TYPE "payload_type"
#define ESP111_PROTOCOL_JSON_ERROR_CODE "error_code"
#define ESP111_PROTOCOL_JSON_MESSAGE "message"

#define ESP111_PROTOCOL_LOCAL_DEVICE_ID_C51 1U
#define ESP111_PROTOCOL_LOCAL_DEVICE_ID_C52 2U

/* C5 <-> S3 轻量 JSON 字段名与本地类型/命令/错误码。 */
#define ESP111_PROTOCOL_LOCAL_JSON_PROTOCOL_VERSION "p"
#define ESP111_PROTOCOL_LOCAL_JSON_ID "id"
#define ESP111_PROTOCOL_LOCAL_JSON_TYPE "t"
#define ESP111_PROTOCOL_LOCAL_JSON_UPTIME_MS "u"
#define ESP111_PROTOCOL_LOCAL_JSON_SEQ "q"
#define ESP111_PROTOCOL_LOCAL_JSON_PAYLOAD_TYPE "pt"
#define ESP111_PROTOCOL_LOCAL_JSON_TIME_SYNCED "ts"
#define ESP111_PROTOCOL_LOCAL_JSON_ROOM_ID "rid"
#define ESP111_PROTOCOL_LOCAL_JSON_ROOM_NAME "rn"
#define ESP111_PROTOCOL_LOCAL_JSON_SENSOR_KIND "s"
#define ESP111_PROTOCOL_LOCAL_JSON_HEALTH_SUBTYPE "h"
#define ESP111_PROTOCOL_LOCAL_JSON_WIFI_RSSI "r"
#define ESP111_PROTOCOL_LOCAL_JSON_VOICE_EVENT "e"
#define ESP111_PROTOCOL_LOCAL_JSON_CSI_KIND "k"
#define ESP111_PROTOCOL_LOCAL_JSON_AUDIO_FORMAT "f"
#define ESP111_PROTOCOL_LOCAL_JSON_VALUES "v"
#define ESP111_PROTOCOL_LOCAL_JSON_COMMAND_ID "cid"
#define ESP111_PROTOCOL_LOCAL_JSON_COMMAND_CODE "c"
#define ESP111_PROTOCOL_LOCAL_JSON_COMMAND_ARGS "a"
#define ESP111_PROTOCOL_LOCAL_JSON_OK "ok"
#define ESP111_PROTOCOL_LOCAL_JSON_ERROR "e"
#define ESP111_PROTOCOL_LOCAL_JSON_COMMANDS "cmds"

#define ESP111_PROTOCOL_DEVICE_STREAM_MAX_BYTES 128U
#define ESP111_PROTOCOL_DEVICE_STREAM_UDP_PORT 33434U
#define ESP111_PROTOCOL_DEVICE_STREAM_JSON_TIMESTAMP "t"
#define ESP111_PROTOCOL_DEVICE_STREAM_JSON_DEVICE_ID "did"
#define ESP111_PROTOCOL_DEVICE_STREAM_JSON_TYPE "type"
#define ESP111_PROTOCOL_DEVICE_STREAM_JSON_LINK_ID "lid"
#define ESP111_PROTOCOL_DEVICE_STREAM_JSON_VALUE1 "v1"
#define ESP111_PROTOCOL_DEVICE_STREAM_JSON_VALUE2 "v2"
#define ESP111_PROTOCOL_DEVICE_STREAM_JSON_VALUE3 "v3"
#define ESP111_PROTOCOL_DEVICE_STREAM_TYPE_CSI "csi"
#define ESP111_PROTOCOL_DEVICE_STREAM_TYPE_SENSOR "sensor"
#define ESP111_PROTOCOL_DEVICE_STREAM_TYPE_STATUS "status"
#define ESP111_PROTOCOL_DEVICE_STREAM_TYPE_EVENT "event"

#define ESP111_PROTOCOL_LOCAL_TYPE_REGISTER "reg"
#define ESP111_PROTOCOL_LOCAL_TYPE_HEARTBEAT "hb"
#define ESP111_PROTOCOL_LOCAL_TYPE_STATUS "st"
#define ESP111_PROTOCOL_LOCAL_TYPE_BME690 "bme"
#define ESP111_PROTOCOL_LOCAL_TYPE_CSI_RESULT "csi"

/* Numeric C5 -> S3 packet types. S3 keeps accepting the string constants above during migration. */
#define ESP111_PROTOCOL_LOCAL_PACKET_SENSOR 1U
#define ESP111_PROTOCOL_LOCAL_PACKET_HEALTH 2U
#define ESP111_PROTOCOL_LOCAL_PACKET_VOICE 3U
#define ESP111_PROTOCOL_LOCAL_PACKET_CMD_ACK 4U
#define ESP111_PROTOCOL_LOCAL_PACKET_CSI 5U

#define ESP111_PROTOCOL_LOCAL_SENSOR_KIND_BME690 1U

#define ESP111_PROTOCOL_LOCAL_HEALTH_REGISTER 1U
#define ESP111_PROTOCOL_LOCAL_HEALTH_HEARTBEAT 2U
#define ESP111_PROTOCOL_LOCAL_HEALTH_STATUS 3U

#define ESP111_PROTOCOL_LOCAL_VOICE_EVENT_TURN_FINISHED 1U
#define ESP111_PROTOCOL_LOCAL_AUDIO_FORMAT_PCM_S16LE_MONO_16K 1U

#define ESP111_PROTOCOL_LOCAL_COMMAND_NOOP 1U
#define ESP111_PROTOCOL_LOCAL_COMMAND_SHOW_TEXT 2U
#define ESP111_PROTOCOL_LOCAL_COMMAND_PLAY_AUDIO 3U
#define ESP111_PROTOCOL_LOCAL_COMMAND_SET_VOLUME 4U
#define ESP111_PROTOCOL_LOCAL_COMMAND_CONFIG_SET 5U
#define ESP111_PROTOCOL_LOCAL_COMMAND_UNSUPPORTED 255U

#define ESP111_PROTOCOL_LOCAL_ERROR_NONE 0U
#define ESP111_PROTOCOL_LOCAL_ERROR_COMMAND_FAILED 1U
#define ESP111_PROTOCOL_LOCAL_ERROR_UNSUPPORTED_COMMAND 2U
#define ESP111_PROTOCOL_LOCAL_ERROR_INVALID_PAYLOAD 3U
#define ESP111_PROTOCOL_LOCAL_ERROR_TIMEOUT 4U
#define ESP111_PROTOCOL_LOCAL_ERROR_UNKNOWN 255U

#define ESP111_PROTOCOL_MSG_REGISTER "device.register"
#define ESP111_PROTOCOL_MSG_HEARTBEAT "device.heartbeat"
#define ESP111_PROTOCOL_MSG_STATUS "device.status"
#define ESP111_PROTOCOL_MSG_SENSOR_BME690 "sensor.bme690"
#define ESP111_PROTOCOL_MSG_CSI_RESULT "csi.result"
#define ESP111_PROTOCOL_MSG_CSI_MOTION "csi.motion"
#define ESP111_PROTOCOL_MSG_COMMAND_ACK "command.ack"
#define ESP111_PROTOCOL_MSG_DASHBOARD_SNAPSHOT "gateway.dashboard_snapshot"

/* C5 <-> S3 本地 HTTP 路径，由 ESPS3/local_http_server 暴露。 */
#define ESP111_PROTOCOL_LOCAL_BASE "/local/v1"
#define ESP111_PROTOCOL_ROUTE_HEALTH "/local/v1/health"
#define ESP111_PROTOCOL_ROUTE_REGISTER "/local/v1/register"
#define ESP111_PROTOCOL_ROUTE_HEARTBEAT "/local/v1/heartbeat"
#define ESP111_PROTOCOL_ROUTE_STATUS "/local/v1/status"
#define ESP111_PROTOCOL_ROUTE_SENSOR "/local/v1/sensor"
#define ESP111_PROTOCOL_ROUTE_CSI_RESULT "/local/v1/csi/result"
#define ESP111_PROTOCOL_ROUTE_DEVICE_STREAM "/local/v1/stream"
#define ESP111_PROTOCOL_ROUTE_VOICE_TURN "/local/v1/voice/turn"
#define ESP111_PROTOCOL_ROUTE_VOICE_PROMPT_CACHE "/local/v1/voice/prompt-cache"
#define ESP111_PROTOCOL_ROUTE_WAKE_PROMPT_AUDIO "/local/v1/audio/wake-prompt"
#define ESP111_PROTOCOL_ROUTE_COMMANDS_PENDING "/local/v1/commands/pending"
#define ESP111_PROTOCOL_ROUTE_COMMANDS_PREFIX "/local/v1/commands/"
#define ESP111_PROTOCOL_ROUTE_COMMAND_ACK_SUFFIX "/ack"
#define ESP111_PROTOCOL_ROUTE_COMMAND_ACK_WILDCARD "/local/v1/commands/*/ack"

/* 语音边界：C5 上传/接收 PCM，S3 只代理，ASR/LLM/TTS 具体实现位于 Server 侧。 */
#ifndef VOICE_REQUEST_TIMEOUT_MS
#define VOICE_REQUEST_TIMEOUT_MS 90000U
#endif
#define ESP111_PROTOCOL_AUDIO_CONTENT_TYPE_L16_16K_MONO \
    "audio/L16; rate=16000; channels=1"
#define ESP111_PROTOCOL_AUDIO_RESPONSE_CONTENT_TYPE "audio/L16"
#define ESP111_PROTOCOL_AUDIO_FORMAT_PCM_S16LE_MONO_16K "pcm_s16le_mono_16k"

#define ESP111_PROTOCOL_ERROR_INVALID_ENVELOPE "invalid_envelope"
#define ESP111_PROTOCOL_ERROR_INVALID_DEVICE_ID "invalid_device_id"
#define ESP111_PROTOCOL_ERROR_INVALID_HEARTBEAT "invalid_heartbeat"
#define ESP111_PROTOCOL_ERROR_INVALID_CSI_RESULT "invalid_csi_result"
#define ESP111_PROTOCOL_ERROR_INVALID_COMMAND_ID "invalid_command_id"
#define ESP111_PROTOCOL_ERROR_INTERNAL "internal_error"
#define ESP111_PROTOCOL_ERROR_COMMAND_POLL_FAILED "command_poll_failed"
#define ESP111_PROTOCOL_ERROR_ACK_FAILED "ack_failed"
#define ESP111_PROTOCOL_ERROR_INVALID_ACK "invalid_ack"
#define ESP111_PROTOCOL_ERROR_INVALID_VOICE_PAYLOAD "invalid_voice_payload"
#define ESP111_PROTOCOL_ERROR_INVALID_COMMAND_PAYLOAD "invalid_command_payload"
#define ESP111_PROTOCOL_ERROR_PAYLOAD_TOO_LARGE "payload_too_large"
#define ESP111_PROTOCOL_ERROR_VOICE_BUSY "voice_busy"
#define ESP111_PROTOCOL_ERROR_GATEWAY_OFFLINE "gateway_offline"
#define ESP111_PROTOCOL_ERROR_TIMEOUT "timeout"
#define ESP111_PROTOCOL_ERROR_SERVER_UNAVAILABLE "server_unavailable"
#define ESP111_PROTOCOL_ERROR_SERVER_REJECTED "server_rejected"
#define ESP111_PROTOCOL_ERROR_ADAPTER "adapter_error"
#define ESP111_PROTOCOL_ERROR_COMMAND_FAILED "command_failed"
#define ESP111_PROTOCOL_ERROR_UNSUPPORTED_COMMAND "unsupported_command"
#define ESP111_PROTOCOL_ERROR_UNKNOWN "unknown"

#ifdef __cplusplus
}
#endif

#endif /* ESP111_PROTOCOL_COMMON_H */
